/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mychat;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sashank
 */
public class Window extends javax.swing.JFrame {

     String url = "jdbc:oracle:thin:@localhost:1521:xe";
        String user = "mychat";
        String pass = "password";
        long id ;
        int flag = 0;
    /**
     * Creates new form Window
     */
    public Window(long i) {
        id = i;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        number_label = new javax.swing.JLabel();
        ph_no_field = new javax.swing.JTextField();
        send_request = new javax.swing.JToggleButton();
        name_label = new javax.swing.JLabel();
        name_field = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        accept_requests = new javax.swing.JToggleButton();
        load_requests = new javax.swing.JToggleButton();
        requests_list = new java.awt.List();
        delete_requests = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        contact_list = new java.awt.List();
        Load_contacts = new javax.swing.JToggleButton();
        Chat = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        number_label.setText("NUMBER");

        send_request.setText("Send Request");
        send_request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_requestActionPerformed(evt);
            }
        });

        name_label.setText("Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(number_label, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(send_request)
                    .addComponent(ph_no_field)
                    .addComponent(name_field, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ph_no_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(send_request)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Contacts", jPanel1);

        accept_requests.setText("Accept Request");
        accept_requests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept_requestsActionPerformed(evt);
            }
        });

        load_requests.setText("Load requests");
        load_requests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load_requestsActionPerformed(evt);
            }
        });

        delete_requests.setText("Delete Request");
        delete_requests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_requestsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(requests_list, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accept_requests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(load_requests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete_requests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(load_requests)
                .addGap(18, 18, 18)
                .addComponent(accept_requests)
                .addGap(18, 18, 18)
                .addComponent(delete_requests)
                .addGap(83, 83, 83))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(requests_list, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Requests", jPanel2);

        Load_contacts.setText("Load Contacts");
        Load_contacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Load_contactsActionPerformed(evt);
            }
        });

        Chat.setText("Chat");
        Chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(contact_list, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Load_contacts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Chat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(contact_list, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(Load_contacts)
                        .addGap(34, 34, 34)
                        .addComponent(Chat)))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Contacts", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void send_requestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_requestActionPerformed
        Connection con=null; 
        try {
             DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
             
             
             //Reference to connection interface
             con = DriverManager.getConnection(url,user,pass);
             long user = Long.parseLong(ph_no_field.getText());
             String name = name_field.getText();
             String sql = "SELECT * from users";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while( rs.next()){
                long i = rs.getLong("id");
                if((i == Long.parseLong(ph_no_field.getText())))
                {
                    flag = 1;
                }
            }
            if(flag == 1)
            {
                int f = 0;
                sql = "INSERT INTO send VALUES("+id+","+user+",'"+name+"')";
                int m = st.executeUpdate(sql);
                if(m == 1)
                {
                    f++;
                }
                sql = "INSERT INTO receive VALUES("+user+","+id+")";
                m = st.executeUpdate(sql);
                if(m==1)
                {
                    f++;
                }
                if(f == 2)
                {
                     JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame,"request sent");
                }
                else
                {
                     JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame,"Please Try again");
                }
            }
            if(flag == 0)
            {
                JFrame frame1 = new JFrame();
             JOptionPane.showMessageDialog(frame1,"Wrong Number");
            }
            con.close();
             // TODO add your handling code here:
         } catch (SQLException ex) {
             Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_send_requestActionPerformed

    private void accept_requestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept_requestsActionPerformed
        Connection con=null;
        
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            int f = 0;
            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
            long num = Long.parseLong(requests_list.getSelectedItem());
            String n= JOptionPane.showInputDialog("Please input name: "); 
            String sql = "insert into contacts values("+id+","+num+",'"+n+"')";
            
            Statement st = con.createStatement();
            int m = st.executeUpdate(sql);
            
            if(m==1)
            {
                f++;
            }
            if(m==0)
            {
                System.out.println("error");
            }
            sql = "select name from send where id = "+num+"and sent = "+id;
            ResultSet rs = st.executeQuery(sql);
            rs.next();
            n = rs.getString("name");
            
            sql = "insert into contacts values("+num+","+id+",'"+n+ "')";
            st = con.createStatement();
            m = st.executeUpdate(sql);
            if(m==1)
            {
                f++;
            }
            sql = "delete from send where id = "+num;
            m = st.executeUpdate(sql);
            if(m==1)
            {
                f++;
            }
            sql = "delete from receive where id = "+id;
            m = st.executeUpdate(sql);
            if(m==1)
            {
                f++;
            }
            if(f == 4)
            {
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame,"Contact Added");
            }
            else
            {
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame,"Please try again");
            }
            
        }
        catch(Exception ex)
        {
            System.err.println(ex);
        }        
        // TODO add your handling code here:
    }//GEN-LAST:event_accept_requestsActionPerformed

    private void load_requestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load_requestsActionPerformed
        Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
 
            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
            String sql = "SELECT received from receive";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            requests_list.removeAll();
            while(rs.next())
            {
                long request = rs.getLong("received");
                requests_list.add(Long.toString(request));
                
            }
            con.close();
        }
        catch(Exception ex)
        {
            System.err.println(ex);
        }        

        // TODO add your handling code here:
    }//GEN-LAST:event_load_requestsActionPerformed

    private void delete_requestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_requestsActionPerformed
     Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            int f = 0;
            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
            long num = Long.parseLong(requests_list.getSelectedItem());
           Statement st = con.createStatement();
            String sql = "delete from send where id = "+num;
            int m = st.executeUpdate(sql);
            if(m==1)
            {
                f++;
            }
            sql = "delete from receive where id = "+id;
            m = st.executeUpdate(sql);
            if(m==1)
            {
                f++;
            }
            if(f == 2)
            {
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame,"Request Deleted");
            }
            else
            {
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame,"Please try again");
            }
            con.close();
        }
        catch(Exception ex)
        {
            System.err.println(ex);
        }        
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_requestsActionPerformed

    private void Load_contactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Load_contactsActionPerformed
    Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
 
            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
           String sql = "SELECT name from contacts where id = "+id;
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            contact_list.removeAll();
            while(rs.next())
            {
                String name = rs.getString("name");
                contact_list.add(name);
                
            }
            con.close();
        }
        catch(Exception ex)
        {
            System.err.println(ex);
        }        
        // TODO add your handling code here:
    }//GEN-LAST:event_Load_contactsActionPerformed

    private void ChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChatActionPerformed
        
        
Connection con=null;
        try
        {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
           String co = contact_list.getSelectedItem();
            //Reference to connection interface
            con = DriverManager.getConnection(url,user,pass);
            String sql = "SELECT contact from contacts where id ="+id+"and name = '"+co+"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            rs.next();
            long d = rs.getLong("contact");
     Chat c = new Chat(id,d);
        c.setVisible(true);
        c.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
          
            con.close();
        }
         catch(Exception ex)
        {
            System.err.println(ex);
        }    
        // TODO add your handling code here:
    }//GEN-LAST:event_ChatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Chat;
    private javax.swing.JToggleButton Load_contacts;
    private javax.swing.JToggleButton accept_requests;
    private java.awt.List contact_list;
    private javax.swing.JToggleButton delete_requests;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton load_requests;
    private javax.swing.JTextField name_field;
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel number_label;
    private javax.swing.JTextField ph_no_field;
    private java.awt.List requests_list;
    private javax.swing.JToggleButton send_request;
    // End of variables declaration//GEN-END:variables
}
